const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 15.99,
    img: "/images/item-1.jpeg",
    desc: `Fluffy stacks of golden perfection – our buttermilk pancakes are a breakfast dream come true.`,
  },
  {
    id: 2,
    title: "dinner double",
    category: "lunch",
    price: 13.99,
    img: "/images/item-2.jpeg",
    desc: `Savor the juiciness of our beef burger, perfectly paired with crispy fries – a classic indulgence.`,
  },
  {
    id: 3,
    title: "godzilla milkshake",
    category: "shakes",
    price: 6.99,
    img: "/images/item-3.jpeg",
    desc: `Indulge in the colossal delight of our Godzilla Milkshake – a towering blend of epic flavors!`,
  },
  {
    id: 4,
    title: "country delight",
    category: "breakfast",
    price: 20.99,
    img: "/images/item-4.jpeg",
    desc: `Delight in a sunrise on your plate – fried egg, bread, and cheese harmonize in perfection.`,
  },
  {
    id: 5,
    title: "egg attack",
    category: "lunch",
    price: 22.99,
    img: "/images/item-5.jpeg",
    desc: `Satisfy your cravings with our egg burger, a delectable blend of flavors topped with fresh salad.`,
  },
  {
    id: 6,
    title: "oreo dream",
    category: "shakes",
    price: 18.99,
    img: "/images/item-6.jpeg",
    desc: `Indulge in the Oreo Dream shake – a creamy blend of cookies and dreams in every sip.`,
  },
  {
    id: 7,
    title: "bacon overflow",
    category: "breakfast",
    price: 8.99,
    img: "/images/item-7.jpeg",
    desc: `Savor the Bacon Overflow delight: a tempting fusion of bagel and egg scramble, a breakfast masterpiece.`,
  },
  {
    id: 8,
    title: "american classic",
    category: "lunch",
    price: 12.99,
    img: "/images/item-8.jpeg",
    desc: `Experience the American Classic: golden fries perfectly paired with a juicy burger, a timeless culinary delight.`,
  },
  {
    id: 9,
    title: "quarantine buddy",
    category: "shakes",
    price: 16.99,
    img: "/images/item-9.jpeg",
    desc: `Quarantine Buddy shake: a comforting blend of flavors to sweeten your solitude, a delightful companion always.`,
  },
];
export default menu;
